language: node_js
node_js:
  - "node"
addons:
  apt:
    packages:
    - librsvg2-bin
script:
  - PACKAGE_VERSION=$(node -pe "require('./package.json').version")  #Get version from package.json
  - echo $PACKAGE_VERSION
  - sed -i "s/[0-9]\+\.[0-9]\+\.[0-9]\+/$PACKAGE_VERSION/" src/app/buildInfo.ts  #replace version in buildInfo.ts

#buildNumber: 1,     TRAVIS_BUILD_NUMBER
#buildUrl: 'https://travis-ci.org/tdillon/ranger/builds/232250457',    TRAVIS_BUILD_ID
#commit: 'cf988d2',     TRAVIS_COMMIT
#repoUrl: 'https://github.com/tdillon/ranger/commit/cf988d2f8d4c6d82fe80ecc4c2352a3b9abb1aa9'   TRAVIS_COMMIT

  - rsvg-convert -v
  - ./create-icons.sh
  - npm run lint
  - npm run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: dist
  