language: node_js
node_js:
  - "node"
addons:
  apt:
    packages:
    - librsvg2-bin
before_script:
  - npm install -g gulp
script:
  - rsvg -v
  - ./create-icons.sh
  - ng build --prod --aot --base-href='/ranger/'
  - gulp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: dist
  