language: node_js
node_js:
  - "node"
addons:
  apt:
    packages:
    - librsvg2-bin
script:
  - rsvg-convert -v
  - ./create-icons.sh
  - npm run lint
  - npm run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: dist
  