language: node_js
node_js:
  - "node"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y librsvg2-bin
  - sudo rsvg -v
before_script:
  - npm install -g gulp
script:
  - ./create-icons.sh
  - ng build --prod --aot --base-href='/ranger/'
  - gulp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: dist
  