language: node_js
node_js:
  - "node"
addons:
  apt:
    packages:
    - librsvg2-bin
script:
  # Get version from package.json.
  - PACKAGE_VERSION=$(node -pe "require('./package.json').version")
  # Write out build info variables.
  - echo $PACKAGE_VERSION
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_BUILD_ID
  - echo $TRAVIS_COMMIT
  # Update buildInfo.ts with build info.
  - sed -i "s/[0-9]\+\.[0-9]\+\.[0-9]\+/$PACKAGE_VERSION/" src/app/buildInfo.ts
  - sed -i "s/\(buildNumber.*\)[0-9]\+/\1$TRAVIS_BUILD_NUMBER/" src/app/buildInfo.ts
  - sed -i "s/\(buildUrl.*builds\/\)[0-9]\+/\1$TRAVIS_BUILD_ID/" src/app/buildInfo.ts
  - sed -i "s/\(commit:.*\)[a-fA-F0-9]\+/\1$TRAVIS_COMMIT/" src/app/buildInfo.ts
  - sed -i "s/\(repoUrl.*commit\/\)[a-fA-F0-9]\+/\1$TRAVIS_COMMIT/" src/app/buildInfo.ts
  # Create icons.
  - rsvg-convert -v
  - ./create-icons.sh
  # Lint code.
  - npm run lint
  # Production build.
  - npm run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: dist
  